// AUTO-GENERATED - DO NOT EDIT
// Generated by scripts/sync-products.ts

export interface ProductDisplay {
  title: string;
  subtitle?: string;
  badge: string | null;
  features: string[];
  highlighted: boolean;
  cta: string;
}

export interface GeneratedProduct {
  slug: string;
  productId: string | null;
  name: string;
  type: "subscription" | "one_time" | "free";
  display: ProductDisplay;
}

export const sandboxProducts: GeneratedProduct[] = [
  {
    slug: "eniem",
    productId: "4d5c4e71-2041-496b-b8cc-f72443e34f48",
    name: "ENIEM",
    type: "one_time",
    display: {
      title: "ENIEM",
      subtitle: "One-time product",
      badge: null,
      features: [],
      highlighted: false,
      cta: "Buy Now",
    },
  },
  {
    slug: "eniem-github",
    productId: "fbd24ddc-323c-468e-aeca-ef0898acc547",
    name: "ENIEM GitHub",
    type: "one_time",
    display: {
      title: "ENIEM GitHub",
      subtitle: "One-time product",
      badge: null,
      features: [],
      highlighted: false,
      cta: "Buy Now",
    },
  },
  {
    slug: "pro-monthly",
    productId: "d221378e-c19a-4f5e-9efb-52d06dcda288",
    name: "Pro Monthly",
    type: "subscription",
    display: {
      title: "Basic Plan",
      subtitle: "Billed monthly",
      badge: null,
      features: ["Your first feature benefit","Your second feature benefit","Your third feature benefit"],
      highlighted: false,
      cta: "Get Started",
    },
  },
  {
    slug: "pro-yearly",
    productId: "3c3e4211-ef96-4861-a939-7bbd8d3c629b",
    name: "Pro Yearly",
    type: "subscription",
    display: {
      title: "Pro Plan",
      subtitle: "Billed yearly",
      badge: "Best Value",
      features: ["Your first feature benefit","Your second feature benefit","Your third feature benefit","Additional yearly benefit"],
      highlighted: true,
      cta: "Get Started",
    },
  }
] as const;

export const productionProducts: GeneratedProduct[] = [
  {
    slug: "pro-monthly",
    productId: null,
    name: "Pro Monthly",
    type: "subscription",
    display: {
      title: "Basic Plan",
      subtitle: "Billed monthly",
      badge: null,
      features: ["Your first feature benefit","Your second feature benefit","Your third feature benefit"],
      highlighted: false,
      cta: "Get Started",
    },
  },
  {
    slug: "pro-yearly",
    productId: null,
    name: "Pro Yearly",
    type: "subscription",
    display: {
      title: "Pro Plan",
      subtitle: "Billed yearly",
      badge: "Best Value",
      features: ["Your first feature benefit","Your second feature benefit","Your third feature benefit","Additional yearly benefit"],
      highlighted: true,
      cta: "Get Started",
    },
  }
] as const;

export function getProducts(env: "sandbox" | "production"): GeneratedProduct[] {
  return env === "sandbox" ? sandboxProducts : productionProducts;
}

/**
 * BetterAuth checkout products format
 * Only includes products with a valid polarProductId
 */
export function getCheckoutProducts(env: "sandbox" | "production") {
  return getProducts(env)
    .filter((p) => p.productId !== null)
    .map((p) => ({
      productId: p.productId as string,
      slug: p.slug,
    }));
}

/**
 * Get products formatted for pricing page display
 * Only includes products intended for display (with valid features)
 */
export function getDisplayProducts(env: "sandbox" | "production") {
  return getProducts(env).filter((p) => p.display.features.length > 0);
}
