name: CI

on:
  pull_request:
    branches: [main, quality]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile

      - run: cp apps/boilerplate/.env.example apps/boilerplate/.env

      - run: pnpm turbo lint typecheck test --filter=...[origin/quality]
